# Basic
title: Shizhan's World
subtitle: To be continued...
welcome_message: o̖⸜((̵̵́ ̆͒͟˚̩̭ ̆͒)̵̵̀)⸝o̗ Hooray！
description: Machine Learning| Data Mining| Frontend| Quant Invest
creator: <a href="http://sz88888.github.io">Shizhan</a>

url: "http://sz88888.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: My Article
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: test, description: Search Me, url: 'http://zszdata.com/DigitalViz/gaode/gaode_echart.html'}
    # - {title: Google Me, description: Google Me, url: 'https://www.google.com/search?source=hp&ei=kCV8XNCPIuOflwS-wqSADQ&q=sz88888.github&btnK=Google+%E6%90%9C%E7%B4%A2&oq=sz88888.github&gs_l=psy-ab.3...2295.12810..13465...9.0..0.84.1172.21......0....1..gws-wiz.....6..35i39j0j0i67j0i12j0i203j0i10j0i10i30j0i30j0i5i10i30.HpheLGRM7z0'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: Project List, description: Click Here, url: 'http://http://zszdata.com/DigitalViz'}

    # - {title: test, description: Search Me, url: 'http://zszdata.com/DigitalViz/gaode/gaode_echart.html'}
# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus:
    # duoshuo:

# Social
social:
    #weibo: 微博小助手
    github: sz88888
    #twitter:
    #gplus:
    mail: shizhan96@gmail.com

# Google Analytics
ga:
     id: UA-135534497-1
    # host: your_host
