# Basic
title: Shizhan's World
subtitle: 能写中文吗
welcome_message: 欢迎
description: wowow
creator: <a href="www.google.com">creator</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: My Article
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Google, description: My WEB, url: 'http://www.google.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus:
    # duoshuo:

# Social
social:
    weibo: 微博小助手
    github: sz88888
    #twitter: onevcat
    #gplus:
    mail: shizhan96@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
